# Generated by Django 5.0.3 on 2024-11-13 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=180)),
                ("phone", models.CharField(max_length=40, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("position", models.CharField(max_length=155)),
                ("salary", models.IntegerField()),
                ("joinning_date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employess",
                        to="home.company",
                    ),
                ),
            ],
        ),
    ]
