# Generated by Django 5.0.3 on 2024-11-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="companytype",
            field=models.CharField(
                choices=[
                    ("Software House", "Software House"),
                    ("PVT LTD", "PVT LTD"),
                    ("Solar Panal", "Solar Panal"),
                ],
                default="exit",
                max_length=300,
            ),
            preserve_default=False,
        ),
    ]
